/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 */

#include <stdint.h>
#include "sdcard.h"
#include "st7789.h"
#include "file_browser.h"
#include "grbl_com.h"
#include <stdio.h>
#include <string.h>

#define USE_INPUT_PC_COM    0
#define USE_INPUT_BUTTON    1

#if USE_INPUT_PC_COM == 1
#include "pc_com.h"
#endif

#if USE_INPUT_BUTTON == 1
#include "button.h"
#endif

typedef enum {
    STATE_HOMING,        
    STATE_SELECT_FILE,   
    STATE_JOGGING,       
    STATE_STREAMING      
} CNC_State_t;

CNC_State_t cnc_state = STATE_SELECT_FILE; 

#define GCODE_LINE_BUFFER_SIZE 256
char line_buffer[GCODE_LINE_BUFFER_SIZE];
static char prev_jog_key = 0; 

// Hàm dùng chung để khóa máy khi bị lỗi (Căn chỉnh cho 240x320)
void CNC_Halt_Error(const char* msg)
{
    ST7789_Fill_Color(RED);
    ST7789_WriteString(10, 100, "LOI / ALARM!", Font_16x26, WHITE, RED);
    ST7789_WriteString(10, 140, msg, Font_11x18, YELLOW, RED);
    ST7789_WriteString(10, 220, "An Reset de K.dong", Font_11x18, WHITE, RED);
    while(1);
}

int main(void)
{
  if (SysTick_Config(SystemCoreClock / 1000)) { while (1); }

  #if USE_INPUT_PC_COM == 1
  PC_COM_Init(115200);
  #endif

  #if USE_INPUT_BUTTON == 1
  Button_Init();
  #endif

  GRBL_Init(115200);     
  ST7789_Init();
  InitSdcard();
  Browser_Init();

  while (1)
  {
      char key = 0;

      #if USE_INPUT_PC_COM == 1
      key = PC_COM_ReceiveByte_NonBlocking();
      #endif

      #if USE_INPUT_BUTTON == 1
      if (key == 0) {
          if (cnc_state == STATE_JOGGING) {
              key = Button_Scan_Continuous(); 
          } else {
              key = Button_Scan_Single();     
          }
      }
      #endif

      switch (cnc_state)
      {
          case STATE_HOMING:
          {
              ST7789_Fill_Color(BLACK);
              ST7789_WriteString(20, 150, "DANG VE GOC...", Font_11x18, YELLOW, BLACK);
              
              GRBL_SendString("$H\n");
              if (GRBL_WaitForOK() == 2) {
                  CNC_Halt_Error("Loi Homing"); 
              }

              ST7789_Fill_Color(BLACK);
              Browser_Init(); 
              cnc_state = STATE_SELECT_FILE;
              break;
          }

          case STATE_SELECT_FILE:
          {
              if (key != 0) Browser_ProcessInput(key);

              if (flag_file_selected == 1)
              {
                  flag_file_selected = 0; 
                  
                  // -- Căn chỉnh lại Menu Jogging cho màn 240x320 --
                  ST7789_Fill_Color(BLACK);
                  ST7789_WriteString(10, 30, "FILE DA CHON:", Font_11x18, WHITE, BLACK);
                  ST7789_WriteString(10, 55, selected_gcode_file, Font_16x26, GREEN, BLACK);
                  
                  ST7789_WriteString(10, 110, "SET GOC PHOI (JOG)", Font_11x18, YELLOW, BLACK);
                  ST7789_WriteString(20, 140, "W/S: Truc Y", Font_11x18, WHITE, BLACK);
                  ST7789_WriteString(20, 165, "A/D: Truc X", Font_11x18, WHITE, BLACK);
                  ST7789_WriteString(20, 190, "I/K: Truc Z", Font_11x18, WHITE, BLACK);

                  // Vẽ một nút ấn giả lập để nhấn mạnh phím chốt tọa độ
                  ST7789_DrawFilledRectangle(0, 250, ST7789_WIDTH, 30, RED);
                  ST7789_WriteString(20, 256, "An 'E' de CHOT GOC", Font_11x18, WHITE, RED);

                  cnc_state = STATE_JOGGING;

                  GRBL_SendString("\n"); GRBL_WaitForOK();
                  GRBL_SendString("\n"); GRBL_WaitForOK();
                  GRBL_SendString("$x\n"); GRBL_WaitForOK();
              }
              break;
          }

          case STATE_JOGGING:
          {
              if (key != prev_jog_key)
              {
                  if (key != 0 && key != 'e')
                  {
                      if (key == 'a')      { GRBL_SendString("$J=G91 X-1000.0 F1500\n"); }
                      else if (key == 'd') { GRBL_SendString("$J=G91 X1000.0 F1500\n"); }
                      else if (key == 'w') { GRBL_SendString("$J=G91 Y1000.0 F1500\n"); }
                      else if (key == 's') { GRBL_SendString("$J=G91 Y-1000.0 F1500\n"); }
                      else if (key == 'i') { GRBL_SendString("$J=G91 Z1000.0 F800\n");  }
                      else if (key == 'k') { GRBL_SendString("$J=G91 Z-1000.0 F800\n");  }

                      if (GRBL_WaitForOK() == 2) CNC_Halt_Error("Loi Cham Bien");
                  }
                  else if (key == 0 && prev_jog_key != 'e')
                  {
                      GRBL_SendChar('\x85');
                  }
                  prev_jog_key = key; 
              }

              if (key == 'e') 
              {
                  GRBL_SendString("G92 X0 Y0 Z0\n");
                  if (GRBL_WaitForOK() == 2) CNC_Halt_Error("Loi G92");

                  cnc_state = STATE_STREAMING;
                  prev_jog_key = 0; 
              }
              break;
          }

          case STATE_STREAMING:
          {
              FIL fil;
              _mountSdcard();
              
              if (f_open(&fil, selected_gcode_file, FA_READ) == FR_OK)
              {
                  uint32_t total_size = f_size(&fil); 
                  uint32_t current_pos = 0;
                  uint8_t last_percent = 255; 
                  char prog_str[20];

                  // -- Căn chỉnh lại Menu Đang chạy (Streaming) cho 240x320 --
                  ST7789_Fill_Color(BLUE);
                  ST7789_WriteString(16, 50, "DANG CHAY MAY", Font_16x26, WHITE, BLUE);
                  
                  // In tên file bôi chữ Vàng để làm nổi bật
                  ST7789_WriteString(40, 90, selected_gcode_file, Font_11x18, YELLOW, BLUE);
                  
                  // Vẽ viền thanh Progress Bar (Rộng 200px, chừa viền 20px mỗi bên)
                  ST7789_DrawRectangle(19, 139, 220, 161, WHITE); 

                  while (f_gets(line_buffer, GCODE_LINE_BUFFER_SIZE, &fil) != NULL)
                  {
                      // Bổ sung ký tự \n nếu dòng Gcode bị khuyết
                      int len = strlen(line_buffer);
                      if (len > 0 && line_buffer[len-1] != '\n' && line_buffer[len-1] != '\r') 
                      {
                          strcat(line_buffer, "\n"); 
                      }

                      GRBL_SendString(line_buffer);
                      
                      if (GRBL_WaitForOK() == 2) 
                      {
                          f_close(&fil);
                          CNC_Halt_Error("Loi Gcode");
                      }

                      current_pos = f_tell(&fil);
                      uint8_t percent = (uint8_t)((current_pos * 100) / total_size);

                      if (percent != last_percent) 
                      {
                          last_percent = percent;
                          
                          // Dòng chữ % tiến độ
                          sprintf(prog_str, "Tien do: %3d %%", percent);
                          ST7789_WriteString(45, 185, prog_str, Font_11x18, YELLOW, BLUE);

                          // Ruột thanh chạy tiến độ (2px tương đương 1%)
                          uint16_t bar_width = percent * 2; 
                          if (bar_width > 0) {
                              ST7789_DrawFilledRectangle(20, 140, bar_width, 20, GREEN);
                          }
                      }
                  }
                  f_close(&fil);
              }

              // Màn hình xanh báo hoàn thành nằm chính giữa
              ST7789_Fill_Color(GREEN);
              ST7789_WriteString(32, 140, "HOAN THANH!", Font_16x26, BLACK, GREEN);
              for(volatile uint32_t i = 0; i < 20000000; i++); 

              Browser_Init();
              cnc_state = STATE_SELECT_FILE;
              break;
          }
      }
  }
}