/*

@file           : main.c

@author         : Auto-generated by STM32CubeIDE (Modified for Hardcore SD Reset)

@brief          : Main program body
*/

#include <stdint.h>
#include "sdcard.h"
#include "st7789.h"
#include "file_browser.h"
#include "grbl_com.h"
#include <stdio.h>
#include <string.h>
#include "ff.h"

#define USE_INPUT_BUTTON    1

#include "pc_com.h"

#if USE_INPUT_BUTTON == 1
#include "button.h"
#endif


#define MUX_PORT      GPIOA
#define MUX_CTRL_1    GPIO_Pin_0   // Nối với chân S của 74HC157 và 1OE của 125
#define MUX_CTRL_2    GPIO_Pin_1   // Nối với chân 2OE của 74HC125


typedef enum {
STATE_HOMING,
STATE_SELECT_FILE,
STATE_JOGGING,
STATE_STREAMING,
STATE_WIFI_SYNC
} CNC_State_t;




CNC_State_t cnc_state = STATE_SELECT_FILE;

#define GCODE_LINE_BUFFER_SIZE 256
char line_buffer[GCODE_LINE_BUFFER_SIZE];
static char prev_jog_key = 0;



void MUX_Init(void) {
    GPIO_InitTypeDef GPIO_InitStructure;
    RCC_APB2PeriphClockCmd(RCC_APB2Periph_GPIOA, ENABLE);

    GPIO_InitStructure.GPIO_Pin = MUX_CTRL_1 | MUX_CTRL_2;
    GPIO_InitStructure.GPIO_Mode = GPIO_Mode_Out_PP;
    GPIO_InitStructure.GPIO_Speed = GPIO_Speed_50MHz;
    GPIO_Init(MUX_PORT, &GPIO_InitStructure);

    // MẶC ĐỊNH LÚC KHỞI ĐỘNG: STM32 LÀM CHỦ THẺ NHỚ
    // CTRL_1 = 0 (157 chọn A, 125 mở kênh 1)
    // CTRL_2 = 1 (125 khóa kênh 2 của ESP)
    GPIO_ResetBits(MUX_PORT, MUX_CTRL_1); 
    GPIO_SetBits(MUX_PORT, MUX_CTRL_2);   

}


void CNC_Halt_Error(const char* msg)
{
    ST7789_Fill_Color(RED);
    ST7789_WriteString(10, 100, "LOI / ALARM!", Font_16x26, WHITE, RED);
    ST7789_WriteString(10, 140, msg, Font_11x18, YELLOW, RED);
    ST7789_WriteString(10, 220, "An Reset de K.dong", Font_11x18, WHITE, RED);
    while(1);
}

// =========================================================================
// HÀM ĐÁNH THỨC THẺ NHỚ BẠO LỰC (HARDCORE BIT-BANGING RESET)
// Giải quyết triệt để lỗi thẻ nhớ bị kẹt trạng thái (Deadlock)
// =========================================================================
void SD_Force_Wakeup(void)
{
    GPIO_InitTypeDef GPIO_InitStructure;

    // Cấp xung nhịp cho GPIOA (Giả sử thẻ SD dùng SPI1: PA4=CS, PA5=SCK, PA7=MOSI)
    RCC_APB2PeriphClockCmd(RCC_APB2Periph_GPIOA, ENABLE);

    // Cấu hình 3 chân điều khiển làm Output Push-Pull
    GPIO_InitStructure.GPIO_Pin = GPIO_Pin_4 | GPIO_Pin_5 | GPIO_Pin_7;
    GPIO_InitStructure.GPIO_Mode = GPIO_Mode_Out_PP;
    GPIO_InitStructure.GPIO_Speed = GPIO_Speed_50MHz;
    GPIO_Init(GPIOA, &GPIO_InitStructure);

    // Macro hỗ trợ Bit-banging cho nhanh
    #define SD_DELAY()  for(volatile int j = 0; j < 20; j++)
    #define SD_SCK_0()  GPIO_ResetBits(GPIOA, GPIO_Pin_5)
    #define SD_SCK_1()  GPIO_SetBits(GPIOA, GPIO_Pin_5)
    #define SD_MOSI_0() GPIO_ResetBits(GPIOA, GPIO_Pin_7)
    #define SD_MOSI_1() GPIO_SetBits(GPIOA, GPIO_Pin_7)
    #define SD_CS_0()   GPIO_ResetBits(GPIOA, GPIO_Pin_4)
    #define SD_CS_1()   GPIO_SetBits(GPIOA, GPIO_Pin_4)

    // 1. ÉP THẺ NHẢ DỮ LIỆU ĐANG KẸT (Flush Read/Write)
    // Kéo CS xuống LOW, bơm 600 xung Clock để rửa trôi mọi bit rác
    SD_CS_0();
    SD_MOSI_1();
    for(int i = 0; i < 600; i++) {
        SD_SCK_0(); SD_DELAY();
        SD_SCK_1(); SD_DELAY();
    }

    // 2. CHUYỂN THẺ VỀ CHẾ ĐỘ SẴN SÀNG NHẬN LỆNH
    // Kéo CS lên HIGH, bơm 80 xung Clock theo chuẩn quốc tế
    SD_CS_1();
    for(int i = 0; i < 80; i++) {
        SD_SCK_0(); SD_DELAY();
        SD_SCK_1(); SD_DELAY();
    }

    // 3. GỬI LỆNH RESET NÓNG (CMD0) BẰNG TAY (BIT-BANGING)
    // Cấu trúc lệnh CMD0: 0x40, 0x00, 0x00, 0x00, 0x00, 0x95 (CRC bắt buộc)
    uint8_t cmd0[6] = {0x40, 0x00, 0x00, 0x00, 0x00, 0x95};
    SD_CS_0(); // Kéo CS thấp để bắt đầu lệnh
    for(int i = 0; i < 6; i++) {
        uint8_t b = cmd0[i];
        for(int bit = 7; bit >= 0; bit--) {
            if((b >> bit) & 1) SD_MOSI_1();
            else SD_MOSI_0();
            
            SD_SCK_0(); SD_DELAY();
            SD_SCK_1(); SD_DELAY();
        }
    }

    // Bơm thêm 16 xung Clock để thẻ có thời gian xử lý lệnh CMD0 vừa nhận
    SD_MOSI_1();
    for(int i = 0; i < 16; i++) {
        SD_SCK_0(); SD_DELAY();
        SD_SCK_1(); SD_DELAY();
    }

    // 4. CHỐT LẠI KẾT THÚC QUÁ TRÌNH DỌN DẸP
    SD_CS_1();
    for(volatile uint32_t i = 0; i < 50000; i++); // Cho thẻ nhớ nghỉ ngơi 1 chút


}
// =========================================================================

int main(void)
{
    if (SysTick_Config(SystemCoreClock / 1000)) { while (1); }

    MUX_Init();

    PC_COM_Init(115200);

    #if USE_INPUT_BUTTON == 1
    Button_Init();
    #endif

    GRBL_Init(115200);
    ST7789_Init();

    // --- GỌI HÀM CẤP CỨU THẺ NHỚ TRƯỚC KHI LÀM BẤT CỨ VIỆC GÌ ---
    // (Lúc này thẻ dù có bị đóng băng kiểu gì cũng bị lôi ra khỏi Deadlock)
    // SD_Force_Wakeup(); 
    // -----------------------------------------------------------

    InitSdcard();
    Browser_Init();

    static char esp_buf[32];
    static uint8_t esp_idx = 0;

    while (1)
    {
        // 1. LẮNG NGHE LỆNH TỪ ESP32 QUA UART2
        char uart_char = PC_COM_ReceiveByte_NonBlocking();
        if (uart_char != 0)
        {
            if (uart_char == '\n' || uart_char == '\r')
            {
                esp_buf[esp_idx] = '\0';

                if (strcmp(esp_buf, "WIFI_REQ") == 0) 
                {
                    // 1. Nhả thẻ nhớ khỏi STM32
                    f_mount(NULL, "", 0); 
                    
                    // 2. GẠT CÔNG TẮC MUX SANG CHO ESP32
                    // CTRL_1 = 1, CTRL_2 = 0
                    GPIO_SetBits(MUX_PORT, MUX_CTRL_1); 
                    GPIO_ResetBits(MUX_PORT, MUX_CTRL_2);
                    
                    // Đợi MUX ổn định điện áp
                    for(volatile uint32_t i = 0; i < 50000; i++); 
                    
                    // 3. Xong xuôi phần cứng mới báo cho ESP32 biết
                    PC_COM_SendString("WIFI_ACK\n");
                    
                    ST7789_Fill_Color(YELLOW);
                    ST7789_WriteString(15, 120, "DANG DONG BO WIFI", Font_16x26, BLACK, YELLOW);
                    ST7789_WriteString(20, 170, "Vui long khong tat may", Font_11x18, BLACK, YELLOW);
                    
                    cnc_state = STATE_WIFI_SYNC;
                }
                else if (strcmp(esp_buf, "WIFI_REL") == 0) 
                {
                    if (cnc_state == STATE_WIFI_SYNC) 
                    {
                        // 1. GẠT CÔNG TẮC MUX LẠI VỀ STM32 TRƯỚC KHI RESET
                        GPIO_ResetBits(MUX_PORT, MUX_CTRL_1); 
                        GPIO_SetBits(MUX_PORT, MUX_CTRL_2);
                        
                        // 2. Báo cho ESP32 biết đã nhận lại thẻ
                        PC_COM_SendString("WIFI_REL_ACK\n"); 
                        
                        // Chờ 1 chút để MUX ổn định và UART gửi hết chữ
                        for(volatile uint32_t i = 0; i < 4000000; i++); 
                        
                        // RESET NÓNG HỆ THỐNG ĐỂ FATFS KHỞI TẠO LẠI TỪ ĐẦU (SẠCH SẼ NHẤT)
                        NVIC_SystemReset(); 
                    }
                }
                esp_idx = 0; 
            } 
            else 
            {
                if (esp_idx < 30) esp_buf[esp_idx++] = uart_char;
            }
        }

        // 2. LẮNG NGHE NÚT BẤM VẬT LÝ
        char key = 0;
        #if USE_INPUT_BUTTON == 1
        if (cnc_state == STATE_JOGGING) {
            key = Button_Scan_Continuous(); 
        } else {
            key = Button_Scan_Single();     
        }
        #endif

        // 3. XỬ LÝ GIAO DIỆN & MÁY CNC
        switch (cnc_state)
        {
            case STATE_WIFI_SYNC:
            {
                break;
            }

            case STATE_HOMING:
            {
                ST7789_Fill_Color(BLACK);
                ST7789_WriteString(20, 150, "DANG VE GOC...", Font_11x18, YELLOW, BLACK);
                
                GRBL_SendString("$H\n");
                if (GRBL_WaitForOK() == 2) {
                    CNC_Halt_Error("Loi Homing"); 
                }

                ST7789_Fill_Color(BLACK);
                Browser_Init(); 
                cnc_state = STATE_SELECT_FILE;
                break;
            }

            case STATE_SELECT_FILE:
            {
                if (key != 0) Browser_ProcessInput(key);

                if (flag_file_selected == 1)
                {
                    flag_file_selected = 0; 
                    
                    ST7789_Fill_Color(BLACK);
                    ST7789_WriteString(10, 30, "FILE DA CHON:", Font_11x18, WHITE, BLACK);
                    ST7789_WriteString(10, 55, selected_gcode_file, Font_16x26, GREEN, BLACK);
                    
                    ST7789_WriteString(10, 110, "SET GOC PHOI (JOG)", Font_11x18, YELLOW, BLACK);
                    ST7789_WriteString(20, 140, "W/S: Truc Y", Font_11x18, WHITE, BLACK);
                    ST7789_WriteString(20, 165, "A/D: Truc X", Font_11x18, WHITE, BLACK);
                    ST7789_WriteString(20, 190, "I/K: Truc Z", Font_11x18, WHITE, BLACK);

                    ST7789_DrawFilledRectangle(0, 250, ST7789_WIDTH, 30, RED);
                    ST7789_WriteString(20, 256, "An 'E' de CHOT GOC", Font_11x18, WHITE, RED);

                    cnc_state = STATE_JOGGING;

                    GRBL_SendString("\n"); GRBL_WaitForOK();
                    GRBL_SendString("\n"); GRBL_WaitForOK();
                    GRBL_SendString("$x\n"); GRBL_WaitForOK();
                }
                break;
            }

            case STATE_JOGGING:
            {
                if (key != prev_jog_key)
                {
                    if (key != 0 && key != 'e')
                    {
                        if (key == 'a')      { GRBL_SendString("$J=G91 X-1000.0 F1500\n"); }
                        else if (key == 'd') { GRBL_SendString("$J=G91 X1000.0 F1500\n"); }
                        else if (key == 'w') { GRBL_SendString("$J=G91 Y1000.0 F1500\n"); }
                        else if (key == 's') { GRBL_SendString("$J=G91 Y-1000.0 F1500\n"); }
                        else if (key == 'i') { GRBL_SendString("$J=G91 Z1000.0 F800\n");  }
                        else if (key == 'k') { GRBL_SendString("$J=G91 Z-1000.0 F800\n");  }

                        if (GRBL_WaitForOK() == 2) CNC_Halt_Error("Loi Cham Bien");
                    }
                    else if (key == 0 && prev_jog_key != 'e')
                    {
                        GRBL_SendChar('\x85');
                    }
                    prev_jog_key = key; 
                }

                if (key == 'e') 
                {
                    GRBL_SendString("G92 X0 Y0 Z0\n");
                    if (GRBL_WaitForOK() == 2) CNC_Halt_Error("Loi G92");

                    cnc_state = STATE_STREAMING;
                    prev_jog_key = 0; 
                }
                break;
            }

            case STATE_STREAMING:
            {
                FIL fil;
                _mountSdcard();
                
                if (f_open(&fil, selected_gcode_file, FA_READ) == FR_OK)
                {
                    uint32_t total_size = f_size(&fil); 
                    uint32_t current_pos = 0;
                    uint8_t last_percent = 255; 
                    char prog_str[20];

                    ST7789_Fill_Color(BLUE);
                    ST7789_WriteString(16, 50, "DANG CHAY MAY", Font_16x26, WHITE, BLUE);
                    ST7789_WriteString(40, 90, selected_gcode_file, Font_11x18, YELLOW, BLUE);
                    ST7789_DrawRectangle(19, 139, 220, 161, WHITE); 

                    while (f_gets(line_buffer, GCODE_LINE_BUFFER_SIZE, &fil) != NULL)
                    {
                        int len = strlen(line_buffer);
                        if (len > 0 && line_buffer[len-1] != '\n' && line_buffer[len-1] != '\r') 
                        {
                            strcat(line_buffer, "\n"); 
                        }

                        GRBL_SendString(line_buffer);
                        
                        if (GRBL_WaitForOK() == 2) 
                        {
                            f_close(&fil);
                            CNC_Halt_Error("Loi Gcode");
                        }

                        current_pos = f_tell(&fil);
                        uint8_t percent = (uint8_t)((current_pos * 100) / total_size);

                        if (percent != last_percent) 
                        {
                            last_percent = percent;
                            sprintf(prog_str, "Tien do: %3d %%", percent);
                            ST7789_WriteString(45, 185, prog_str, Font_11x18, YELLOW, BLUE);

                            uint16_t bar_width = percent * 2; 
                            if (bar_width > 0) {
                                ST7789_DrawFilledRectangle(20, 140, bar_width, 20, GREEN);
                            }
                        }
                    }
                    f_close(&fil);
                }

                ST7789_Fill_Color(GREEN);
                ST7789_WriteString(32, 140, "HOAN THANH!", Font_16x26, BLACK, GREEN);
                for(volatile uint32_t i = 0; i < 20000000; i++); 

                Browser_Init();
                cnc_state = STATE_SELECT_FILE;
                break;
            }
        }
    }

}